name: Madang

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  hello_world_job:
    name: A job to say hello
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Harden Runner
      - name: Harden Runner # Audit all outbound calls
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      # Checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      # Hello world action step
      - name: Hello world action step
        uses: mnrendra/jajal-docker2-action@f16445c6182c63aa17a77d821d8e6d34dd0685ee
        with:
          token: ${{ secrets.TOKEN }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
