name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # Harden Runner
      - name: Harden Runner # Audit all outbound calls
        uses: step-security/harden-runner@0634a2670c59f64b4a01f0f96f84700a4088b9f0 # v2.12.0
        with:
          egress-policy: audit

      # Checkout
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0
          token: ${{ secrets.TOKEN }}

      # Release
      # - name: Release
      #   uses: mnrendra/jajal-docker2-action@f66bd39ee7c74f228aadbabe28fff9694f8b5d7f # v3.0.0
      #   with:
      #     gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
      #     gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
